//! Auto-generated protobuf types for the CoreML specification.
//!
//! This module exposes Rust structs generated by `prost` from the `.proto`
//! files that define Apple's CoreML on-disk format.

// Suppress clippy and missing-docs on machine-generated code.
#[allow(clippy::all, missing_docs, non_camel_case_types, rustdoc::all)]
mod generated {
    /// Types from `package CoreML.Specification` (Model, NeuralNetwork, FeatureTypes, …).
    pub mod core_ml {
        pub mod specification {
            include!(concat!(env!("OUT_DIR"), "/core_ml.specification.rs"));

            /// Additional model types under `CoreML.Specification.CoreMLModels`.
            pub mod core_ml_models {
                include!(concat!(
                    env!("OUT_DIR"),
                    "/core_ml.specification.core_ml_models.rs"
                ));
            }

            /// MIL (Model Intermediate Language) types under `CoreML.Specification.MILSpec`.
            pub mod mil_spec {
                include!(concat!(
                    env!("OUT_DIR"),
                    "/core_ml.specification.mil_spec.rs"
                ));
            }
        }
    }
}

// Re-export so users can reach types without the deeply nested path.
pub use generated::core_ml::specification;
pub use specification::core_ml_models;
pub use specification::mil_spec;

/// Auto-generated types from the ONNX `.proto3` specification.
#[allow(clippy::all, missing_docs, non_camel_case_types, rustdoc::all)]
pub mod onnx {
    include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
}
