//! Auto-generated protobuf types for the CoreML specification.
//!
//! This module exposes Rust structs generated by `prost` from the `.proto`
//! files that define Apple's CoreML on-disk format.

// Suppress clippy and doctests on machine-generated code.
// Proto comments contain pseudo-code blocks that rustdoc tries to compile.
#[allow(clippy::all, non_camel_case_types)]
#[cfg(not(doctest))]
mod generated {
    /// Types from `package CoreML.Specification` (Model, NeuralNetwork, FeatureTypes, …).
    pub mod core_ml {
        pub mod specification {
            include!(concat!(env!("OUT_DIR"), "/core_ml.specification.rs"));

            /// Additional model types under `CoreML.Specification.CoreMLModels`.
            pub mod core_ml_models {
                include!(concat!(
                    env!("OUT_DIR"),
                    "/core_ml.specification.core_ml_models.rs"
                ));
            }

            /// MIL (Model Intermediate Language) types under `CoreML.Specification.MILSpec`.
            pub mod mil_spec {
                include!(concat!(
                    env!("OUT_DIR"),
                    "/core_ml.specification.mil_spec.rs"
                ));
            }
        }
    }
}

// When running doctests the generated module is absent — provide a stub so the
// re-exports below still resolve and the crate's own doctests can compile.
#[cfg(doctest)]
mod generated {
    pub mod core_ml {
        pub mod specification {
            pub mod core_ml_models {}
            pub mod mil_spec {}
        }
    }
}

// Re-export so users can reach types without the deeply nested path.
pub use generated::core_ml::specification;
pub use specification::core_ml_models;
pub use specification::mil_spec;
